import Head from 'next/head'
import { Row, Col } from 'react-bootstrap'

export default function Home() {
  return (
    <Row className='p-5'>

      <Head>
        <title>Home | Palavras de Paz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Col>
        <h1>
          Welcome to <a href="https://www.palavrasdepaz.org/">Palavras de Paz</a>
        </h1>
      </Col>

      <Col>
        <h1>
          Welcome to <a href="https://www.palavrasdepaz.org/">Palavras de Paz</a>
        </h1>
      </Col>

      <Col>
        <h1>
          Welcome to <a href="https://www.palavrasdepaz.org/">Palavras de Paz</a>
        </h1>
      </Col>

    </Row>
  )
}